# Generated by Django 4.2.7 on 2023-11-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='registration_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
